### ISSUE TITLE
[Question] Any way to force this command ?

### ISSUE THREAD

**Issue by nullptrerror** [LayZeeDK/ngx-nrwl-airlines-workspace#1]
json: error: lookups cannot be specified with in-place editing (-I/--in-place), too easy to lose content
npx json -I -f angular.json -e "this.projects['booking-feature-shell'] = this.projects['feature-shell']"

I know I can edit the file but I like the way you used the cmd to change it.

**Comment by LayZeeDK** [comment]
I don't know why sometimes that happen. I didn't experience it after installing it as a development dependency. Did you try to restart your editor/terminal? Also please try installing `json` globally and running the command without npx.

Let me know whether it works out for you.

I'm also happy to take your questions on inDepth.dev Community so that more people can benefit from a solution to a common issue: https://community.indepth.dev/t/tutorial-how-to-set-up-an-nx-style-monorepo-workspace-with-the-angular-cli/521

**Comment by LayZeeDK** [comment]
Which version of Node are you using, which operating system and which terminal?

**Comment by nullptrerror** [comment]
I appreciate the quick reply.
I ran `λ npm install -g json` liked you recommended and it started working right after.
My node version is v13.12.0 and my operating system is Windows 10 N Pro.
`
λ node -v
v13.12.0
`
